"""followers

Revision ID: 962dd5e1dcb6
Revises: 78e98d0ddadb
Create Date: 2023-11-01 12:29:53.023792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '962dd5e1dcb6'
down_revision = '78e98d0ddadb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
